name: push_gem

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'gem version'
        required: true
        default: 'latest'
        type: string

  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  push_gem:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set Credentials
        run: | #gotten from https://michaelheap.com/rubygem-github-package-registry/
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: push gem
        run: 
        | #extra .gem files might be an issue, or irrelevant. Remove if possible. If cannot remove, specify gem to be built instead of *.gem
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/applyboard omniauth-oktaoauth-0.1.6.gem