name: push_gem

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited]
  
  #allows you to run this workflow manually from Actions tab
  workflow_dispatch:
  
jobs:
  ruby_lib_ci:
    uses: ApplyBoard/platform_common_github-action/.github/workflows/ruby_lib_ci.yml@v0.0.3
    with:
      gem_name: omniauth-oktaoauth
      test_on_ruby_3: false
    secrets: inherit