name: push_gem

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
  #allows you to run this workflow manually from Actions tab
  workflow_dispatch:
  
jobs:
  ruby_lib_ci:
    uses: ApplyBoard/platform_common_github-action/.github/workflows/ruby_lib_publish_rc.yml@v0.0.3
    with:
      gem_name: omniauth-oktaoauth-0.1.6
    secrets: inherit